### PR TITLE
bump: akkaserverless-framework 0.7.0-beta.11

### PR DESCRIPTION
**Pull request by patriknw**

### CODE REVIEW

**Comment by johanandren** [comment]
Will require some more work than just the bump (replicated entity changes, new discovery methods etc.)

**Comment by patriknw** [comment]
Right, I'll revive https://github.com/lightbend/akkaserverless-java-sdk/pull/30

**Comment by patriknw** [comment]
Something changed with the startup log messages?

```
2021-07-06 07:21:13,166 INFO  🐳 [gcr.io/akkaserverless-public/akkaserverless-proxy:0.7.0-beta.11] - Container gcr.io/akkaserverless-public/akkaserverless-proxy:0.7.0-beta.11 is starting: e75f6fa8b9764478c158c9ce0da2fe38026d420e14f39334230121438ab441d4
2021-07-06 07:21:17,847 INFO  com.akkaserverless.javasdk.impl.DiscoveryImpl - Received discovery call from [akkaserverless-proxy-core 0.7.0-beta.11] supporting Akka Serverless protocol 0.7
2021-07-06 07:22:13,265 DEBUG 🐳 [gcr.io/akkaserverless-public/akkaserverless-proxy:0.7.0-beta.11] - Wait strategy threw an exception
org.testcontainers.containers.ContainerLaunchException: Timed out waiting for log output matching '.*Akka Serverless proxy online.*'
	at org.testcontainers.containers.wait.strategy.LogMessageWaitStrategy.waitUntilReady(LogMessageWaitStrategy.java:49)
	at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:35)
	at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:892)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:440)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:325)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:323)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:311)
	at com.akkaserverless.javasdk.testkit.AkkaServerlessProxyContainer.start(AkkaServerlessProxyContainer.java:85)
	at com.akkaserverless.javasdk.testkit.AkkaServerlessTestkit.start(AkkaServerlessTestkit.java:134)
	at com.akkaserverless.javasdk.testkit.AkkaServerlessTestkit.start(AkkaServerlessTestkit.java:113)
	at com.akkaserverless.javasdk.testkit.junit.AkkaServerlessTestkitResource.before(AkkaServerlessTestkitResource.java:73)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:50)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
2021-07-06 07:22:13,273 ERROR 🐳 [gcr.io/akkaserverless-public/akkaserverless-proxy:0.7.0-beta.11] - Could not start container
org.testcontainers.containers.ContainerLaunchException: Timed out waiting for log output matching '.*Akka Serverless proxy online.*'
	at org.testcontainers.containers.wait.strategy.LogMessageWaitStrategy.waitUntilReady(LogMessageWaitStrategy.java:49)
	at org.testcontainers.containers.wait.strategy.AbstractWaitStrategy.waitUntilReady(AbstractWaitStrategy.java:35)
	at org.testcontainers.containers.GenericContainer.waitUntilContainerStarted(GenericContainer.java:892)
	at org.testcontainers.containers.GenericContainer.tryStart(GenericContainer.java:440)
	at org.testcontainers.containers.GenericContainer.lambda$doStart$0(GenericContainer.java:325)
	at org.rnorth.ducttape.unreliables.Unreliables.retryUntilSuccess(Unreliables.java:81)
	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:323)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:311)
	at com.akkaserverless.javasdk.testkit.AkkaServerlessProxyContainer.start(AkkaServerlessProxyContainer.java:85)
	at com.akkaserverless.javasdk.testkit.AkkaServerlessTestkit.start(AkkaServerlessTestkit.java:134)
	at com.akkaserverless.javasdk.testkit.AkkaServerlessTestkit.start(AkkaServerlessTestkit.java:113)
	at com.akkaserverless.javasdk.testkit.junit.AkkaServerlessTestkitResource.before(AkkaServerlessTestkitResource.java:73)
```

**Comment by pvlugter** [comment]
Log message should be changed to `gRPC proxy started` now (from changes to discovery and health check).

**Pull request merged**
