### PR TITLE
Merging the maven-java project into SDK

### PR DESCRIPTION
**Pull request by octonato**
This brings in the maven-java repo.  This is targeting a feature branch called `rgc/feature-branch-maven-java`.

We may need to simply merge this for now and then continue applying the changes we need to get the CI and other bits the way we want.

Refereces https://github.com/lightbend/akkaserverless-java-sdk/issues/27

(cc @huntc / @RoryStokes)

### CODE REVIEW

**Review by huntc — APPROVED** [review]
Let’s rip the bandaid off!

**Comment by pvlugter** [comment]
Something I did when breaking out the SDKs from framework, was to strip out the `#XYZ` issue or PR references from commit messages, as these no longer reference the right issues. There are a bunch of references from this PR showing up in other issues currently.

**Comment by octonato** [comment]
> Something I did when breaking out the SDKs from framework, was to strip out the #XYZ issue or PR references from commit messages, as these no longer reference the right issues. There are a bunch of references from this PR showing up in other issues currently.

Yeah, I noticed that. Have your wrote a script to do it or did you edit one by one?

**Comment by octonato** [comment]
I'm merging this since we have one ✅ and that's more ground work.

**Comment by octonato** [comment]
hmm, not merge commit available. Need to change repo's settings.

**Pull request merged**
