### PR TITLE
Add script to publish codegen and maven plugins locally

### PR DESCRIPTION
**Pull request by raboof**
For easier testing

### CODE REVIEW

**Review by octonato — APPROVED** [review]
LGTM

**Comment by octonato** [comment]
CleanShot 2021-07-13 at 15 48 11

CI beautifully shows the job dependency graph, but build fails because artifact not found. 

Anyway, I think this is the structure we want. We now need to find out why the cache is not working as expected.

**Comment by octonato** [comment]
This is failing with a compilation error. 

Sounds that `sdk-codegen-dev` is not compiling anyway.

**Review by johanandren — APPROVED** [review]

**Comment by johanandren** [comment]
@octonato it is now, I fixed it in https://github.com/lightbend/akkaserverless-java-sdk/pull/132

**Pull request merged**
