### PR TITLE
Smaller testkit follow ups

### PR DESCRIPTION
**Pull request by johanandren**
* Move classes to testkit from sdk
 * impl over internal for internal classes
 * Result translated to Java and given Javadocs
 * Warnings in TestKitHelper pattern match fixed

### CODE REVIEW

**Review by patriknw — APPROVED** [review]
LGTM

**Review by octonato — APPROVED** [review]

**Comment by octonato** [comment]
Testing is failing with 

```bash
/bin/bash: line 0: cd: samples/java-customer-registry: No such file or directory

Exited with code exit status 1
CircleCI received exit code 1
```

makes no sense

**Comment by patriknw** [comment]
it was renamed in `main`. Rebase the PR. I had same in one of mine.

**Comment by raboof** [comment]
(correct - the root cause here is that CircleCI uses the circleci config from the PR, but then during the build merges `main` into the local repo - so the build does have the updates to the code from `main`, but not the updates to the circleci config)

**Pull request merged**
