### PR TITLE
build: cache .m2 repository

### PR DESCRIPTION
**Pull request by octonato**
References https://github.com/lightbend/akkaserverless-java-sdk/issues/9

### CODE REVIEW

**Review by ennru — APPROVED** [review]
LGTM.

Is the cache ever dropped?

**Comment by octonato** [comment]
> Is the cache ever dropped?

Good question. I will search about this in the CI docs. They probably do.

**Comment by ennru** [comment]
The link in #9 shows how the keys are made dynamic by hashing certain files: https://circleci.com/docs/2.0/caching/#using-caching-in-monorepos

**Comment by octonato** [comment]
yeah, I saw it. That would mean, a new cache each time we change one of the build files.

But I wasn't sure we needed it.

**Pull request merged**
