### PR TITLE
changing Interface class name to Abstract

### PR DESCRIPTION
**Pull request by franciscolopezsancho**
tested on
- codegen
- maven-java
- single application calling to codegen through maven-java-plugin (maybe unnecessary : )

### CODE REVIEW

**Comment by franciscolopezsancho** [comment]
I think we some dependency issue. The `maven-java-test` that is failing is because they are using the previous codegen which creates `[info] Generated: target/generated-sources/akkaserverless/java/com/example/shoppingcart/domain/ShoppingCartInterface.java
` . Part of this PR is to make sure the maven-java now expects `target/generated-sources/akkaserverless/java/com/example/shoppingcart/domain/AbstractShopping.java`. 

Shall I do this in two steps? Meaning first a PR only to the codegen and later to maven-java?

Or you might prefer to change the CI so it creates first the codegen and uses it?

LMKWYT

**Comment by franciscolopezsancho** [comment]
forget about my last comment, please. Everything should now work, I added the required git dependencies.

**Comment by ennru** [comment]
Fixes #42

**Review by ennru — APPROVED** [review]
LGTM.
A next step could be to remove the `Impl` postfix on the class created for the user.

**Review by johanandren — APPROVED** [review]

**Comment by franciscolopezsancho** [comment]
you mean to remove the `Impl` in this PR @ennru ?

**Comment by ennru** [comment]
> you mean to remove the `Impl` in this PR

No, let's do that in another PR.

**Pull request merged**
