### PR TITLE
chore: wrap whole docker-compose with Velocity escaping

### PR DESCRIPTION
**Pull request by octonato**
References #783

### CODE REVIEW

**Review by raboof — APPROVED** [review]
actually I wonder if it wouldn't be nice to use the velocity templating to replace the akkaserverless-proxy version, but until then no objection :+1:

**Comment by octonato** [comment]
> actually I wonder if it wouldn't be nice to use the velocity templating to replace the akkaserverless-proxy version, but until then no objection

I don't think it has much value to ask user which version of the proxy they want to use. At the end, they should use what is deployed by us.

**Comment by raboof** [comment]
> > actually I wonder if it wouldn't be nice to use the velocity templating to replace the akkaserverless-proxy version, but until then no objection
> 
> I don't think it has much value to ask user which version of the proxy they want to use. At the end, they should use what is deployed by us.

I agree we shouldn't ask the user, but it would be convenient if we didn't have to update this version in so many places when doing a proxy release - I figured the templating might allow us to 'inherit' it from the build somehow. Perhaps that's not so easy though - anyway not important.

**Comment by octonato** [comment]
We have some scripts to that update the versions for the sdk. They are not in good shape. We have two of them and they overlap. We could review them and include the dockers as well. We will still need to run them after a release though.

**Pull request merged**
