### PR TITLE
fix: base on codegen for ShoppingCart in eventing example

### PR DESCRIPTION
**Pull request by ennru**
This PR retrofits use of codegen on the Eventing Shopping Cart example code, which is used for documentation snippets.﻿

Codegen uses different defaults than this example did.

The `ShoppingCartEntity` implementation moves into the `shopping.cart.domain` package and now extends the codgen-generated abstract base class which consistently returns `Reply`.

Similar changes are required for the `ProductPopularityEntity` and the `ShoppingCartView`.

### CODE REVIEW

**Comment by ennru** [comment]
#199 must be fixed to use the View codegen in the sample

https://github.com/lightbend/akkaserverless-java-sdk/blob/7944836c27414bd96961245c1d09b86c727c393b/samples/java-eventing-shopping-cart/src/main/java/shopping/cart/ShoppingCartView.java#L34-L38

**Review by patriknw — COMMENTED** [review]
@raboof Do you know the status here?

**Comment by raboof** [comment]
Not really, but it looks like the next step is to fix #199 . Adding a comment there as well :)

**Comment by ennru** [comment]
This succeeds on CI as the View implementation lives in `shopping.cart.ShoppingCartView` (which uses `UpdateHandlerContext` see #199) whereas codegen creates an empty `shopping.cart.view.ShoppingCartViewServiceView`.

**Comment by ennru** [comment]
Not relevant anymore.

**Pull request closed without merging**
