### PR TITLE
rename: adapt to run against new proxy protocols

### PR DESCRIPTION
**Pull request by jrudolph**

### CODE REVIEW

**Review by octonato — APPROVED** [review]
LGTM

**Comment by jrudolph** [comment]
Several issues right now:

 * we need to add snapshot repository to every project to make use of a snapshot proxy
 * tck seems to be broken but more likely because of postgres / yugabyte than because of the renaming it seems

**Comment by jrudolph** [comment]
https://github.com/lightbend/kalix-proxy/pull/1306 will help with the TCK problems

**Comment by jrudolph** [comment]
All tests green :fireworks:

**Pull request merged**
