### PR TITLE
fix: deserializing EventSourced entity events

### PR DESCRIPTION
**Pull request by raboof**

### CODE REVIEW

**Comment by jrudolph** [comment]
Will be easy to create a test case for this once #753 is merged.

**Comment by raboof** [comment]
> Will be easy to create a test case for this once #753 is merged.

Yes, actually I was surprised our unit test data didn't catch this since I think this should be the typical scenario...

**Comment by jrudolph** [comment]
I just checked the TCK which didn't fail because it uses the same type for events and state.

**Comment by jrudolph** [comment]
> Yes, actually I was surprised our unit test data didn't catch this since I think this should be the typical scenario...

The unusual part is that state and events are defined in different files.

**Comment by raboof** [comment]
> The unusual part is that state and events are defined in different files.

Aaah good eyes :+1:

**Review by johanandren — APPROVED** [review]

**Pull request merged**
